// Turkish user data constants
export const ADDITIONAL_TURKISH_USERS = [
  {
    id: "3b7c8e6e-1a2f-4a87-84b1-9e2f5c671b1a",
    name: "Ahmet Yılmaz",
    username: "ahmety",
    email: "ahmet.yilmaz@example.com",
    address: {
      street: "Çiçek Sokak",
      suite: "Daire 3",
      city: "İstanbul",
      zipcode: "34000",
      geo: { lat: "41.0082", lng: "28.9784" },
    },
    phone: "0532-111-2233",
    website: "ahmetyilmaz.com",
    company: {
      name: "Yılmaz Teknoloji",
      catchPhrase: "Yenilikçi dijital çözümler",
      bs: "modern yazılım altyapıları geliştir",
    },
  },
  {
    id: "b4f9c0de-6f84-4d4b-a64f-8218af51f382",
    name: "Elif Demir",
    username: "elifd",
    email: "elif.demir@example.com",
    address: {
      street: "Menekşe Caddesi",
      suite: "Apt. 5",
      city: "Ankara",
      zipcode: "06000",
      geo: { lat: "39.9208", lng: "32.8541" },
    },
    phone: "0544-555-6677",
    website: "elifdemir.net",
    company: {
      name: "Demir Yazılım",
      catchPhrase: "Verimliliği artıran sistemler",
      bs: "kurumsal çözümler üret",
    },
  },
  {
    id: "6a9f03d5-5f41-422e-b74e-3d8a8f542b28",
    name: "Can Kaya",
    username: "cank",
    email: "can.kaya@example.com",
    address: {
      street: "Gül Sokak",
      suite: "No: 12",
      city: "İzmir",
      zipcode: "35000",
      geo: { lat: "38.4192", lng: "27.1287" },
    },
    phone: "0507-123-4567",
    website: "cankaya.dev",
    company: {
      name: "Kaya Bilişim",
      catchPhrase: "Yazılımda güvenin adresi",
      bs: "teknolojik altyapıları optimize et",
    },
  },
  {
    id: "b03a40c1-ef2a-41ed-98ef-7f2542d14de8",
    name: "Zeynep Aydın",
    username: "zeynepa",
    email: "zeynep.aydin@example.com",
    address: {
      street: "Sahil Yolu",
      suite: "Kat: 2",
      city: "Antalya",
      zipcode: "07000",
      geo: { lat: "36.8969", lng: "30.7133" },
    },
    phone: "0555-987-6543",
    website: "zeynepaydin.org",
    company: {
      name: "Aydın Turizm",
      catchPhrase: "Tatilde huzurun adresi",
      bs: "seyahat planlaması yap",
    },
  },
  {
    id: "89a3fa1a-511c-4c59-9f2e-99887097d692",
    name: "Mehmet Koç",
    username: "mehmetk",
    email: "mehmet.koc@example.com",
    address: {
      street: "Papatya Mahallesi",
      suite: "No: 22",
      city: "Bursa",
      zipcode: "16000",
      geo: { lat: "40.1885", lng: "29.0610" },
    },
    phone: "0533-888-9999",
    website: "mehmetkoc.biz",
    company: {
      name: "Koç Mühendislik",
      catchPhrase: "Güvenilir mühendislik çözümleri",
      bs: "inşaat süreçlerini dijitalleştir",
    },
  },
  {
    id: "c57407b4-3b1a-4b89-84a2-79f26a9776e5",
    name: "Ayşe Çelik",
    username: "aysec",
    email: "ayse.celik@example.com",
    address: {
      street: "Karanfil Sokak",
      suite: "Daire 8",
      city: "Adana",
      zipcode: "01000",
      geo: { lat: "37.0022", lng: "35.3213" },
    },
    phone: "0543-112-2233",
    website: "aysecelik.com",
    company: {
      name: "Çelik Tasarım",
      catchPhrase: "Yaratıcı tasarımlar bir tık uzağında",
      bs: "markalar için dijital kimlik oluştur",
    },
  },
  {
    id: "9f6e3df7-cfd3-4f68-83a7-5a16ee7585d7",
    name: "Ali Can",
    username: "alican",
    email: "ali.can@example.com",
    address: {
      street: "Cumhuriyet Caddesi",
      suite: "No: 45",
      city: "Konya",
      zipcode: "42000",
      geo: { lat: "37.8667", lng: "32.4833" },
    },
    phone: "0506-444-5566",
    website: "alican.dev",
    company: {
      name: "Can Web",
      catchPhrase: "Basit, hızlı, güvenli çözümler",
      bs: "modern web siteleri oluştur",
    },
  },
  {
    id: "f873a801-0bb3-4e43-8b5a-b8bda911504e",
    name: "Derya Polat",
    username: "deryap",
    email: "derya.polat@example.com",
    address: {
      street: "Yeşil Sokak",
      suite: "Daire 9",
      city: "Trabzon",
      zipcode: "61000",
      geo: { lat: "41.0015", lng: "39.7178" },
    },
    phone: "0541-333-8899",
    website: "deryapolat.me",
    company: {
      name: "Polat Danışmanlık",
      catchPhrase: "Geleceğe yön veren çözümler",
      bs: "veri analizinde fark yarat",
    },
  },
  {
    id: "67a0b5d3-1d23-4026-9183-6bdecb43e92f",
    name: "Emre Şahin",
    username: "emres",
    email: "emre.sahin@example.com",
    address: {
      street: "Güneş Caddesi",
      suite: "No: 14",
      city: "Gaziantep",
      zipcode: "27000",
      geo: { lat: "37.0662", lng: "37.3833" },
    },
    phone: "0530-222-3344",
    website: "emresahin.tech",
    company: {
      name: "Şahin Yazılım",
      catchPhrase: "Hızlı ve etkili çözümler",
      bs: "yazılım süreçlerini otomatize et",
    },
  },
  {
    id: "ab3de428-692c-4df7-8e7a-bbb4056c8cb9",
    name: "Fatma Er",
    username: "fatmae",
    email: "fatma.er@example.com",
    address: {
      street: "Kordonboyu",
      suite: "Kat: 5",
      city: "İzmir",
      zipcode: "35210",
      geo: { lat: "38.4237", lng: "27.1428" },
    },
    phone: "0551-777-8899",
    website: "fatmaer.org",
    company: {
      name: "Er Medya",
      catchPhrase: "Yaratıcılığın adresi",
      bs: "markalar için medya çözümleri üret",
    },
  },
  {
    id: "fb62b6d4-d8da-4205-9e2f-4c55b9318232",
    name: "Hakan Güneş",
    username: "hakang",
    email: "hakan.gunes@example.com",
    address: {
      street: "Yıldız Mahallesi",
      suite: "No: 10",
      city: "Eskişehir",
      zipcode: "26000",
      geo: { lat: "39.7767", lng: "30.5206" },
    },
    phone: "0505-666-7788",
    website: "hakangunes.net",
    company: {
      name: "Güneş Teknoloji",
      catchPhrase: "Her zaman bir adım önde",
      bs: "akıllı cihaz yazılımları geliştir",
    },
  },
  {
    id: "89c51b54-85a4-44c8-9d5f-76d55df94771",
    name: "Selin Arslan",
    username: "selina",
    email: "selin.arslan@example.com",
    address: {
      street: "Orman Sokak",
      suite: "No: 6",
      city: "Samsun",
      zipcode: "55000",
      geo: { lat: "41.2928", lng: "36.3313" },
    },
    phone: "0534-222-1133",
    website: "selinarslan.co",
    company: {
      name: "Arslan Studio",
      catchPhrase: "Tasarımda fark yarat",
      bs: "markalar için görsel kimlik geliştir",
    },
  },
  {
    id: "5fddc8db-8356-46c9-9a12-19bde6c63cc3",
    name: "Burak Taş",
    username: "burakt",
    email: "burak.tas@example.com",
    address: {
      street: "Kale Sokak",
      suite: "No: 2",
      city: "Kayseri",
      zipcode: "38000",
      geo: { lat: "38.7333", lng: "35.4833" },
    },
    phone: "0507-999-2211",
    website: "buraktas.dev",
    company: {
      name: "Taş Web",
      catchPhrase: "Modern web deneyimi",
      bs: "front-end çözümleri geliştir",
    },
  },
  {
    id: "2c987ac1-2f1b-4b7a-8c1a-7dcb6d69ec44",
    name: "Melisa Korkmaz",
    username: "melisak",
    email: "melisa.korkmaz@example.com",
    address: {
      street: "Deniz Sokak",
      suite: "Kat: 3",
      city: "Muğla",
      zipcode: "48000",
      geo: { lat: "37.2153", lng: "28.3636" },
    },
    phone: "0550-888-1122",
    website: "melisakorkmaz.com",
    company: {
      name: "Korkmaz Dijital",
      catchPhrase: "Yeni nesil içerik üretimi",
      bs: "sosyal medya çözümleri sun",
    },
  },
  {
    id: "b8478c87-82a5-4bde-a5cf-64049a3c377d",
    name: "Onur Aksoy",
    username: "onura",
    email: "onur.aksoy@example.com",
    address: {
      street: "Mevlana Caddesi",
      suite: "No: 18",
      city: "Konya",
      zipcode: "42030",
      geo: { lat: "37.8715", lng: "32.4848" },
    },
    phone: "0538-321-6549",
    website: "onuraksoy.tech",
    company: {
      name: "Aksoy Elektronik",
      catchPhrase: "Teknolojiyi kolaylaştırıyoruz",
      bs: "akıllı cihaz entegrasyonu yap",
    },
  },
  {
    id: "92ec83de-fef7-46d7-bd3f-1b8b4cde24b8",
    name: "Nazlı Eren",
    username: "nazlie",
    email: "nazli.eren@example.com",
    address: {
      street: "Bahçe Mahallesi",
      suite: "No: 9",
      city: "Balıkesir",
      zipcode: "10000",
      geo: { lat: "39.6484", lng: "27.8826" },
    },
    phone: "0541-223-5566",
    website: "nazlieren.org",
    company: {
      name: "Eren Creative",
      catchPhrase: "Sanat ve teknoloji bir arada",
      bs: "marka tasarımları üret",
    },
  },
  {
    id: "2e3217f4-1df7-48c2-a3e8-90c5d8b0cf76",
    name: "Cem Karaca",
    username: "cemk",
    email: "cem.karaca@example.com",
    address: {
      street: "Atatürk Bulvarı",
      suite: "Kat: 7",
      city: "Mersin",
      zipcode: "33000",
      geo: { lat: "36.8121", lng: "34.6415" },
    },
    phone: "0505-777-4433",
    website: "cemkaraca.me",
    company: {
      name: "Karaca Yazılım",
      catchPhrase: "Her kod bir hikaye anlatır",
      bs: "kreatif yazılım projeleri geliştir",
    },
  },
  {
    id: "0fb6b093-11a3-48d5-a46e-2c81e91ed6cb",
    name: "Ebru Öz",
    username: "ebruo",
    email: "ebru.oz@example.com",
    address: {
      street: "Gökçe Sokak",
      suite: "No: 5",
      city: "Çanakkale",
      zipcode: "17000",
      geo: { lat: "40.1553", lng: "26.4142" },
    },
    phone: "0552-999-8887",
    website: "ebruoz.co",
    company: {
      name: "Öz İletişim",
      catchPhrase: "Bağlantının gücünü keşfet",
      bs: "iletişim altyapılarını geliştir",
    },
  },
  {
    id: "b31732a2-295f-4c62-9ebd-9e99fbb9f6d8",
    name: "Mert Bozkurt",
    username: "mertb",
    email: "mert.bozkurt@example.com",
    address: {
      street: "Zümrüt Sokak",
      suite: "No: 15",
      city: "Denizli",
      zipcode: "20000",
      geo: { lat: "37.7742", lng: "29.0875" },
    },
    phone: "0544-443-2233",
    website: "mertbozkurt.dev",
    company: {
      name: "Bozkurt Systems",
      catchPhrase: "Geleceği kodluyoruz",
      bs: "otomasyon yazılımları geliştir",
    },
  },
  {
    id: "05f5b121-b96b-462b-8025-2f9f4726e479",
    name: "Seda Kılıç",
    username: "sedak",
    email: "seda.kilic@example.com",
    address: {
      street: "Yeni Mahalle",
      suite: "Daire 2",
      city: "Tekirdağ",
      zipcode: "59000",
      geo: { lat: "40.9781", lng: "27.5119" },
    },
    phone: "0542-665-4433",
    website: "sedakilic.net",
    company: {
      name: "Kılıç Yazılım",
      catchPhrase: "Teknolojide öncü çözümler",
      bs: "mobil uygulama geliştir",
    },
  },
];
