import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.scss";
import ToastProvider from "../components/providers/ToastProvider";
import QueryProvider from "../components/providers/QueryProvider";
import ModalProvider from "../components/providers/ModalProvider";
import { Header, Body, LayoutWrapper } from "../components/layout";
import { HeaderContent } from "../components/layout/HeaderContent";
import logo from "./logo.webp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning={true}
      >
        <QueryProvider>
          <ToastProvider>
            <ModalProvider>
              <LayoutWrapper>
                <Header>
                  <HeaderContent logo={logo} />
                </Header>
                <Body>{children}</Body>
              </LayoutWrapper>
            </ModalProvider>
          </ToastProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
